# Generated by Django 4.2.7 on 2023-11-24 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='comentario',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
