# Generated by Django 4.2.7 on 2023-11-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0002_historico_comentario_alter_receita_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='comentario',
        ),
        migrations.AddField(
            model_name='historico',
            name='avaliacao',
            field=models.CharField(choices=[('P', 'Péssimo'), ('R', 'Ruim'), ('B', 'Bom'), ('O', 'Ótimo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
