# Generated by Django 4.2.7 on 2023-11-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_remove_historico_comentario_historico_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
