# Generated by Django 4.2.7 on 2023-11-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0004_alter_historico_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_receita'),
        ),
    ]
