# Generated by Django 4.2.7 on 2023-11-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0005_receita_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='rendimento',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='tempo_de_preparo',
        ),
    ]
