# Generated by Django 4.2.7 on 2023-11-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0010_avaliacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
